### ISSUE TITLE
Support // for empty fraction.

### ISSUE THREAD

**Issue by mohkale** [tecosaur/LaTeX-auto-activating-snippets#12]
The README for this package suggests binding `//` to an empty fraction snippet but that won't work with the current implementation because it interferes with the `/` snippet. I'd suggest allowing the `/` snippet to support `//` as well. Thoughts?

**Comment by ymarco** [comment]
I'm not technically against this, but the implementation of laas-identify-adjacent-tex-object is already spaghetti enough.

I personally already have a yasnippet with / as a key that expands to \frac{$1}{$2}$0. This is a parallel to that, requiring // instead of /<TAB> to expand the snippet.

The snippet in the readme is supposed to be more of a showcase of how you can empower yas with aas, not really a suggestion. Perhaps it should be replaced.

Anyway, I'd have no problem accepting this if you refactor laas-identify-adjacent-tex-object for us.

**Comment by mohkale** [comment]
@ymarco 

> I personally already have a yasnippet with / as a key that expands to \frac{$1}{$2}$0. This is a parallel to that, requiring // instead of /<TAB> to expand the snippet.

Interesting... although I think // will be more intuitive than `/<TAB>` once you get used to it.

> Anyway, I'd have no problem accepting this if you refactor laas-identify-adjacent-tex-object for us.

No problem. I'll look into this a little later if that's all right. Thnx.
