### ISSUE TITLE
Modification of laas-identify-adjacent-tex-object to avoid error

### ISSUE THREAD

**Issue by jsilve24** [tecosaur/LaTeX-auto-activating-snippets#26]
To find error:

Make a new buffer, make the first chacters in buffer $A$. 

Put point on right side of A and type `/`. 

Get an error `eval: Wrong type argument: number-or-marker-p, nil`. 

This modification should fix that. 

```
(defun laas-identify-adjacent-tex-object (&optional point)
  "Return the starting position of the left-adjacent TeX object from POINT."
  (save-excursion
    (goto-char (or point (point)))
    (cond
     ((memq (char-before) '(?\) ?\] ?\$)) ; add $ environment symbol
      (backward-sexp)
      (point))
     ((= (char-before) ?})
      (cl-loop do (backward-sexp)
               while (= (char-before) ?}))
      ;; try to catch the marco if the braces belong to one
      (when (looking-back "\\\\[A-Za-z@*]+" (line-beginning-position))
        (goto-char (match-beginning 0)))
      (when (memq (char-before) '(?_ ?^ ?.))
        (backward-char)
        (goto-char (laas-identify-adjacent-tex-object))) ; yay recursion
      (point))
     ((or (<= ?a (char-before) ?z)
          (<= ?A (char-before) ?Z)
          (<= ?0 (char-before) ?9))
      (backward-word)
      (when
	  (when (char-before) 		; make sure there is char before :)
	    (= (char-before) ?\\) (backward-char)))
      (when (memq (char-before) '(?_ ?^ ?.))
        (backward-char)
        (goto-char (laas-identify-adjacent-tex-object))) ; yay recursion
      (point))))
```

Its a corner case, still, figured I would try to patch.

**Comment by ymarco** [comment]
References: ***@***.***>
User-agent: mu4e 1.6.3; emacs 28.0.60
In-reply-to: ***@***.***>
Note: in my reproducing code the snippet expands to \frac{$A}{}$ since $ is skipped together with A in the call to (backward-word) on line 118 (https://github.com/tecosaur/LaTeX-auto-activating-snippets/blob/397bde14/laas.el#L118) but that doesn't happen in proper latex-mode where the syntax table is set correctly.
Thanks for the report!
Justin Silverman ***@***.***> writes:
  (with-temp-buffer
    (setq major-mode 'org-mode) ; to trick laas-math with math syntax
    (yas-minor-mode +1)
    (laas-mode +1)
    (insert "$A/$")
    (backward-char)
    (aas-expand-snippet-maybe "/" #'laas-smart-fraction #'laas-frac-cond)
    (buffer-string))

I can reproduce the error with


>      ((memq (char-before) '(?\) ?\] ?\$)) ; add $ environment symbol

Why is this needed? I can't figure this out.

> 	  (when (char-before) 		; make sure there is char before :)
> 	    (= (char-before) ?\\) (backward-char)))

Performing this change only is enough for me to avoid the error.

(It does happen in org-mode but you should use \(\) instead of $$ in org anyway as I understand but )

**Comment by jsilve24** [comment]
Re the memq line: Acctually, perhaps that line should not be in there. I can't decide as I am not solid enough on the code. I figured that the way the function was currently written it was not robust to the $A$ or $$A$$ syntax... Perhaps I misunderstood.

**Comment by ymarco** [comment]
(Seems like my mail was garbled, I edited and the comment should be readable now)
